#!/bin/bash

# ═══════════════════════════════════════════════════════════════════
# Epic 8 ECS Fargate Deployment Script
# ═══════════════════════════════════════════════════════════════════
#
# This script automates the complete deployment of Epic 8 RAG Platform
# to AWS ECS Fargate with 3-tier model routing.
#
# Usage:
#   ./deploy.sh [command]
#
# Commands:
#   setup       - Create all infrastructure (VPC, ECS, ALB, etc.)
#   build       - Build and push Docker images
#   deploy      - Deploy services to ECS
#   teardown    - Delete all infrastructure
#   status      - Check deployment status
#   logs        - Tail service logs
#   test        - Run end-to-end tests
#
# Prerequisites:
#   - AWS CLI configured
#   - Docker running
#   - HuggingFace token set
#   - Ollama running with ngrok tunnel
#
# ═══════════════════════════════════════════════════════════════════

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_NAME="epic8"
AWS_REGION="${AWS_REGION:-us-east-1}"
CLUSTER_NAME="${PROJECT_NAME}-ecs-cluster"
VPC_CIDR="10.0.0.0/16"
SUBNET_CIDR="10.0.1.0/24"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# State file
STATE_FILE="$SCRIPT_DIR/infrastructure-ids.sh"

# ═══════════════════════════════════════════════════════════════════
# Helper Functions
# ═══════════════════════════════════════════════════════════════════

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check AWS CLI
    if ! command -v aws &> /dev/null; then
        log_error "AWS CLI not found. Install with: brew install awscli"
        exit 1
    fi

    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker not found. Install Docker Desktop"
        exit 1
    fi

    # Check Docker daemon
    if ! docker info &> /dev/null; then
        log_error "Docker daemon not running. Start Docker Desktop"
        exit 1
    fi

    # Check AWS credentials
    if ! aws sts get-caller-identity &> /dev/null; then
        log_error "AWS credentials not configured. Run: aws configure"
        exit 1
    fi

    # Check HuggingFace token
    if [[ -z "$HUGGINGFACE_TOKEN" ]]; then
        log_warn "HUGGINGFACE_TOKEN not set. You'll need to set it manually in Secrets Manager"
    fi

    # Check Ollama URL
    if [[ -z "$OLLAMA_URL" ]]; then
        log_warn "OLLAMA_URL not set. You'll need to set it manually in Secrets Manager"
    fi

    log_success "Prerequisites check passed"
}

get_aws_account_id() {
    aws sts get-caller-identity --query Account --output text
}

save_state() {
    local key="$1"
    local value="$2"

    # Create state file if doesn't exist
    if [[ ! -f "$STATE_FILE" ]]; then
        cat > "$STATE_FILE" <<EOF
#!/bin/bash
# Epic 8 Infrastructure IDs
# Generated by deploy.sh
EOF
        chmod +x "$STATE_FILE"
    fi

    # Update or add key
    if grep -q "export $key=" "$STATE_FILE"; then
        sed -i.bak "s|export $key=.*|export $key=\"$value\"|" "$STATE_FILE"
        rm -f "$STATE_FILE.bak"
    else
        echo "export $key=\"$value\"" >> "$STATE_FILE"
    fi
}

load_state() {
    if [[ -f "$STATE_FILE" ]]; then
        source "$STATE_FILE"
        log_info "Loaded state from $STATE_FILE"
    else
        log_warn "No state file found at $STATE_FILE"
    fi
}

# ═══════════════════════════════════════════════════════════════════
# Infrastructure Setup
# ═══════════════════════════════════════════════════════════════════

setup_vpc() {
    log_info "Creating VPC..."

    # Create VPC
    VPC_ID=$(aws ec2 create-vpc \
        --cidr-block $VPC_CIDR \
        --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=${PROJECT_NAME}-vpc},{Key=Project,Value=${PROJECT_NAME}}]" \
        --query 'Vpc.VpcId' \
        --output text \
        --region $AWS_REGION)

    save_state "VPC_ID" "$VPC_ID"
    log_success "VPC created: $VPC_ID"

    # Enable DNS
    aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames --region $AWS_REGION
    aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-support --region $AWS_REGION

    # Create Internet Gateway
    IGW_ID=$(aws ec2 create-internet-gateway \
        --tag-specifications "ResourceType=internet-gateway,Tags=[{Key=Name,Value=${PROJECT_NAME}-igw},{Key=Project,Value=${PROJECT_NAME}}]" \
        --query 'InternetGateway.InternetGatewayId' \
        --output text \
        --region $AWS_REGION)

    save_state "IGW_ID" "$IGW_ID"
    log_success "Internet Gateway created: $IGW_ID"

    # Attach IGW to VPC
    aws ec2 attach-internet-gateway \
        --vpc-id $VPC_ID \
        --internet-gateway-id $IGW_ID \
        --region $AWS_REGION

    # Create Public Subnet
    SUBNET_ID=$(aws ec2 create-subnet \
        --vpc-id $VPC_ID \
        --cidr-block $SUBNET_CIDR \
        --availability-zone ${AWS_REGION}a \
        --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=${PROJECT_NAME}-public-subnet},{Key=Project,Value=${PROJECT_NAME}}]" \
        --query 'Subnet.SubnetId' \
        --output text \
        --region $AWS_REGION)

    save_state "SUBNET_ID" "$SUBNET_ID"
    log_success "Subnet created: $SUBNET_ID"

    # Enable auto-assign public IP
    aws ec2 modify-subnet-attribute \
        --subnet-id $SUBNET_ID \
        --map-public-ip-on-launch \
        --region $AWS_REGION

    # Create Route Table
    RTB_ID=$(aws ec2 create-route-table \
        --vpc-id $VPC_ID \
        --tag-specifications "ResourceType=route-table,Tags=[{Key=Name,Value=${PROJECT_NAME}-public-rtb},{Key=Project,Value=${PROJECT_NAME}}]" \
        --query 'RouteTable.RouteTableId' \
        --output text \
        --region $AWS_REGION)

    save_state "RTB_ID" "$RTB_ID"

    # Create route to IGW
    aws ec2 create-route \
        --route-table-id $RTB_ID \
        --destination-cidr-block 0.0.0.0/0 \
        --gateway-id $IGW_ID \
        --region $AWS_REGION

    # Associate route table with subnet
    aws ec2 associate-route-table \
        --route-table-id $RTB_ID \
        --subnet-id $SUBNET_ID \
        --region $AWS_REGION

    # Create Security Group
    SG_ID=$(aws ec2 create-security-group \
        --group-name ${PROJECT_NAME}-ecs-sg \
        --description "Security group for Epic8 ECS tasks" \
        --vpc-id $VPC_ID \
        --tag-specifications "ResourceType=security-group,Tags=[{Key=Name,Value=${PROJECT_NAME}-ecs-sg},{Key=Project,Value=${PROJECT_NAME}}]" \
        --query 'GroupId' \
        --output text \
        --region $AWS_REGION)

    save_state "SG_ID" "$SG_ID"
    log_success "Security Group created: $SG_ID"

    # Allow inbound from within VPC
    aws ec2 authorize-security-group-ingress \
        --group-id $SG_ID \
        --protocol tcp \
        --port 8000-8003 \
        --cidr $VPC_CIDR \
        --region $AWS_REGION 2>/dev/null || true

    # Allow HTTP from anywhere (for ALB)
    aws ec2 authorize-security-group-ingress \
        --group-id $SG_ID \
        --protocol tcp \
        --port 80 \
        --cidr 0.0.0.0/0 \
        --region $AWS_REGION 2>/dev/null || true

    log_success "VPC setup complete"
}

setup_ecs() {
    log_info "Creating ECS cluster..."

    aws ecs create-cluster \
        --cluster-name $CLUSTER_NAME \
        --capacity-providers FARGATE \
        --default-capacity-provider-strategy capacityProvider=FARGATE,weight=1 \
        --tags key=Project,value=$PROJECT_NAME \
        --region $AWS_REGION

    save_state "CLUSTER_NAME" "$CLUSTER_NAME"
    log_success "ECS cluster created: $CLUSTER_NAME"
}

setup_ecr() {
    log_info "Creating ECR repositories..."

    for service in api-gateway query-analyzer generator analytics; do
        repo_name="${PROJECT_NAME}/${service}"

        # Check if repository exists
        if aws ecr describe-repositories \
            --repository-names $repo_name \
            --region $AWS_REGION &>/dev/null; then
            log_info "ECR repository already exists: $repo_name"
        else
            aws ecr create-repository \
                --repository-name $repo_name \
                --image-scanning-configuration scanOnPush=true \
                --tags Key=Project,Value=$PROJECT_NAME \
                --region $AWS_REGION
            log_success "ECR repository created: $repo_name"
        fi
    done

    # ECR login
    AWS_ACCOUNT_ID=$(get_aws_account_id)
    save_state "AWS_ACCOUNT_ID" "$AWS_ACCOUNT_ID"

    aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin \
        ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

    log_success "ECR setup complete"
}

setup_iam() {
    log_info "Creating IAM roles..."

    # Trust policy
    cat > /tmp/ecs-trust-policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF

    # Create execution role
    if aws iam get-role --role-name ecsTaskExecutionRole --region $AWS_REGION &>/dev/null; then
        log_info "Task execution role already exists"
    else
        aws iam create-role \
            --role-name ecsTaskExecutionRole \
            --assume-role-policy-document file:///tmp/ecs-trust-policy.json \
            --region $AWS_REGION

        aws iam attach-role-policy \
            --role-name ecsTaskExecutionRole \
            --policy-arn arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy \
            --region $AWS_REGION

        # Add Secrets Manager access
        cat > /tmp/secrets-policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["secretsmanager:GetSecretValue"],
      "Resource": "arn:aws:secretsmanager:${AWS_REGION}:*:secret:${PROJECT_NAME}/*"
    }
  ]
}
EOF

        aws iam put-role-policy \
            --role-name ecsTaskExecutionRole \
            --policy-name SecretsManagerAccess \
            --policy-document file:///tmp/secrets-policy.json \
            --region $AWS_REGION

        log_success "Task execution role created"
    fi

    # Create task role
    if aws iam get-role --role-name ecsTaskRole --region $AWS_REGION &>/dev/null; then
        log_info "Task role already exists"
    else
        aws iam create-role \
            --role-name ecsTaskRole \
            --assume-role-policy-document file:///tmp/ecs-trust-policy.json \
            --region $AWS_REGION

        aws iam attach-role-policy \
            --role-name ecsTaskRole \
            --policy-arn arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy \
            --region $AWS_REGION

        log_success "Task role created"
    fi

    TASK_EXECUTION_ROLE_ARN=$(aws iam get-role --role-name ecsTaskExecutionRole --query 'Role.Arn' --output text --region $AWS_REGION)
    TASK_ROLE_ARN=$(aws iam get-role --role-name ecsTaskRole --query 'Role.Arn' --output text --region $AWS_REGION)

    save_state "TASK_EXECUTION_ROLE_ARN" "$TASK_EXECUTION_ROLE_ARN"
    save_state "TASK_ROLE_ARN" "$TASK_ROLE_ARN"

    rm -f /tmp/ecs-trust-policy.json /tmp/secrets-policy.json

    log_success "IAM setup complete"
}

setup_alb() {
    log_info "Creating Application Load Balancer..."

    load_state

    # Create ALB
    ALB_ARN=$(aws elbv2 create-load-balancer \
        --name ${PROJECT_NAME}-alb \
        --subnets $SUBNET_ID \
        --security-groups $SG_ID \
        --scheme internet-facing \
        --type application \
        --ip-address-type ipv4 \
        --tags Key=Project,Value=$PROJECT_NAME \
        --query 'LoadBalancers[0].LoadBalancerArn' \
        --output text \
        --region $AWS_REGION)

    save_state "ALB_ARN" "$ALB_ARN"
    log_success "ALB created: $ALB_ARN"

    # Get ALB DNS
    ALB_DNS=$(aws elbv2 describe-load-balancers \
        --load-balancer-arns $ALB_ARN \
        --query 'LoadBalancers[0].DNSName' \
        --output text \
        --region $AWS_REGION)

    save_state "ALB_DNS" "$ALB_DNS"
    log_success "ALB DNS: http://$ALB_DNS"

    # Create Target Group
    TG_ARN=$(aws elbv2 create-target-group \
        --name ${PROJECT_NAME}-api-gateway-tg \
        --protocol HTTP \
        --port 8000 \
        --vpc-id $VPC_ID \
        --target-type ip \
        --health-check-enabled \
        --health-check-path /health \
        --health-check-interval-seconds 30 \
        --health-check-timeout-seconds 5 \
        --healthy-threshold-count 2 \
        --unhealthy-threshold-count 3 \
        --tags Key=Project,Value=$PROJECT_NAME \
        --query 'TargetGroups[0].TargetGroupArn' \
        --output text \
        --region $AWS_REGION)

    save_state "TG_ARN" "$TG_ARN"
    log_success "Target Group created: $TG_ARN"

    # Create Listener
    aws elbv2 create-listener \
        --load-balancer-arn $ALB_ARN \
        --protocol HTTP \
        --port 80 \
        --default-actions Type=forward,TargetGroupArn=$TG_ARN \
        --region $AWS_REGION

    log_success "ALB setup complete"
}

setup_secrets() {
    log_info "Creating secrets in Secrets Manager..."

    # HuggingFace token
    if [[ -n "$HUGGINGFACE_TOKEN" ]]; then
        aws secretsmanager create-secret \
            --name ${PROJECT_NAME}/huggingface-token \
            --description "HuggingFace API token for Epic8" \
            --secret-string "$HUGGINGFACE_TOKEN" \
            --tags Key=Project,Value=$PROJECT_NAME \
            --region $AWS_REGION 2>/dev/null || \
        aws secretsmanager update-secret \
            --secret-id ${PROJECT_NAME}/huggingface-token \
            --secret-string "$HUGGINGFACE_TOKEN" \
            --region $AWS_REGION

        log_success "HuggingFace token secret created"
    else
        log_warn "HUGGINGFACE_TOKEN not set. Create manually with:"
        log_warn "  aws secretsmanager create-secret --name ${PROJECT_NAME}/huggingface-token --secret-string 'YOUR_TOKEN'"
    fi

    # Ollama URL
    if [[ -n "$OLLAMA_URL" ]]; then
        aws secretsmanager create-secret \
            --name ${PROJECT_NAME}/ollama-url \
            --description "Ollama tunnel URL for Epic8" \
            --secret-string "$OLLAMA_URL" \
            --tags Key=Project,Value=$PROJECT_NAME \
            --region $AWS_REGION 2>/dev/null || \
        aws secretsmanager update-secret \
            --secret-id ${PROJECT_NAME}/ollama-url \
            --secret-string "$OLLAMA_URL" \
            --region $AWS_REGION

        log_success "Ollama URL secret created"
    else
        log_warn "OLLAMA_URL not set. Create manually with:"
        log_warn "  aws secretsmanager create-secret --name ${PROJECT_NAME}/ollama-url --secret-string 'YOUR_NGROK_URL'"
    fi
}

setup_cloudwatch() {
    log_info "Creating CloudWatch log groups..."

    for service in api-gateway query-analyzer generator analytics; do
        log_group="/ecs/${PROJECT_NAME}-${service}"

        # Create log group
        aws logs create-log-group \
            --log-group-name $log_group \
            --region $AWS_REGION 2>/dev/null || true

        # Set retention to 7 days
        aws logs put-retention-policy \
            --log-group-name $log_group \
            --retention-in-days 7 \
            --region $AWS_REGION

        log_success "Log group created: $log_group"
    done
}

# ═══════════════════════════════════════════════════════════════════
# Build and Push Images
# ═══════════════════════════════════════════════════════════════════

build_and_push() {
    log_info "Building and pushing Docker images..."

    load_state

    cd "$PROJECT_ROOT"

    for service in api-gateway query-analyzer generator analytics; do
        log_info "Building $service..."

        service_dir="services/${service//-/_}"
        image_name="${PROJECT_NAME}/${service}"
        ecr_url="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${image_name}:latest"

        # Build
        docker build -t $image_name:latest -f $service_dir/Dockerfile .

        # Tag
        docker tag $image_name:latest $ecr_url

        # Push
        docker push $ecr_url

        log_success "$service image pushed: $ecr_url"
    done

    log_success "All images built and pushed"
}

# ═══════════════════════════════════════════════════════════════════
# Deploy Services
# ═══════════════════════════════════════════════════════════════════

deploy_services() {
    log_info "Deploying ECS services..."

    load_state

    # Register task definitions
    for service in generator api-gateway query-analyzer analytics; do
        register_task_definition $service
    done

    # Create service discovery namespace
    create_service_discovery

    # Deploy services
    deploy_generator
    deploy_api_gateway
    deploy_query_analyzer
    deploy_analytics

    log_success "All services deployed"
    log_info "Access your API at: http://$ALB_DNS"
}

register_task_definition() {
    local service=$1
    log_info "Registering task definition for $service..."

    # Create task definition JSON
    cat > /tmp/${service}-task.json <<EOF
{
  "family": "${PROJECT_NAME}-${service}",
  "networkMode": "awsvpc",
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "256",
  "memory": "512",
  "executionRoleArn": "${TASK_EXECUTION_ROLE_ARN}",
  "taskRoleArn": "${TASK_ROLE_ARN}",
  "containerDefinitions": [
    {
      "name": "${service}",
      "image": "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}/${service}:latest",
      "essential": true,
      "portMappings": [
        {
          "containerPort": 8002,
          "protocol": "tcp"
        }
      ],
      "environment": [
        {"name": "SERVICE_NAME", "value": "${service}"},
        {"name": "PORT", "value": "8002"},
        {"name": "LOG_LEVEL", "value": "INFO"},
        {"name": "AWS_REGION", "value": "${AWS_REGION}"}
      ],
      "secrets": [
        {
          "name": "HUGGINGFACE_TOKEN",
          "valueFrom": "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${PROJECT_NAME}/huggingface-token"
        },
        {
          "name": "OLLAMA_URL",
          "valueFrom": "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${PROJECT_NAME}/ollama-url"
        }
      ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/${PROJECT_NAME}-${service}",
          "awslogs-region": "${AWS_REGION}",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "healthCheck": {
        "command": ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"],
        "interval": 30,
        "timeout": 5,
        "retries": 3,
        "startPeriod": 60
      }
    }
  ]
}
EOF

    aws ecs register-task-definition \
        --cli-input-json file:///tmp/${service}-task.json \
        --region $AWS_REGION

    rm -f /tmp/${service}-task.json

    log_success "Task definition registered for $service"
}

create_service_discovery() {
    log_info "Creating service discovery namespace..."

    # Check if namespace exists
    if NAMESPACE_ID=$(aws servicediscovery list-namespaces \
        --query "Namespaces[?Name=='${PROJECT_NAME}.local'].Id" \
        --output text \
        --region $AWS_REGION) && [[ -n "$NAMESPACE_ID" ]]; then
        log_info "Namespace already exists: $NAMESPACE_ID"
    else
        # Create namespace
        OPERATION_ID=$(aws servicediscovery create-private-dns-namespace \
            --name ${PROJECT_NAME}.local \
            --vpc $VPC_ID \
            --query 'OperationId' \
            --output text \
            --region $AWS_REGION)

        # Wait for namespace creation
        sleep 10

        NAMESPACE_ID=$(aws servicediscovery list-namespaces \
            --query "Namespaces[?Name=='${PROJECT_NAME}.local'].Id" \
            --output text \
            --region $AWS_REGION)

        log_success "Service discovery namespace created: $NAMESPACE_ID"
    fi

    save_state "NAMESPACE_ID" "$NAMESPACE_ID"
}

deploy_generator() {
    log_info "Deploying generator service..."

    # Create service discovery service
    SERVICE_REGISTRY_ARN=$(aws servicediscovery create-service \
        --name generator \
        --dns-config "NamespaceId=${NAMESPACE_ID},DnsRecords=[{Type=A,TTL=60}]" \
        --health-check-custom-config FailureThreshold=1 \
        --query 'Service.Arn' \
        --output text \
        --region $AWS_REGION 2>/dev/null || \
    aws servicediscovery list-services \
        --filters "Name=NAMESPACE_ID,Values=${NAMESPACE_ID}" \
        --query "Services[?Name=='generator'].Arn" \
        --output text \
        --region $AWS_REGION)

    # Create ECS service
    aws ecs create-service \
        --cluster $CLUSTER_NAME \
        --service-name generator \
        --task-definition ${PROJECT_NAME}-generator \
        --desired-count 1 \
        --launch-type FARGATE \
        --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SG_ID],assignPublicIp=ENABLED}" \
        --service-registries "registryArn=${SERVICE_REGISTRY_ARN}" \
        --region $AWS_REGION 2>/dev/null || \
    aws ecs update-service \
        --cluster $CLUSTER_NAME \
        --service generator \
        --task-definition ${PROJECT_NAME}-generator \
        --force-new-deployment \
        --region $AWS_REGION

    log_success "Generator service deployed"
}

deploy_api_gateway() {
    log_info "Deploying API gateway service..."

    # Create ECS service with ALB
    aws ecs create-service \
        --cluster $CLUSTER_NAME \
        --service-name api-gateway \
        --task-definition ${PROJECT_NAME}-api-gateway \
        --desired-count 1 \
        --launch-type FARGATE \
        --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SG_ID],assignPublicIp=ENABLED}" \
        --load-balancers "targetGroupArn=$TG_ARN,containerName=api-gateway,containerPort=8000" \
        --health-check-grace-period-seconds 120 \
        --region $AWS_REGION 2>/dev/null || \
    aws ecs update-service \
        --cluster $CLUSTER_NAME \
        --service api-gateway \
        --task-definition ${PROJECT_NAME}-api-gateway \
        --force-new-deployment \
        --region $AWS_REGION

    log_success "API Gateway service deployed"
}

deploy_query_analyzer() {
    log_info "Deploying query analyzer service..."

    # Create service discovery service
    SERVICE_REGISTRY_ARN=$(aws servicediscovery create-service \
        --name query-analyzer \
        --dns-config "NamespaceId=${NAMESPACE_ID},DnsRecords=[{Type=A,TTL=60}]" \
        --health-check-custom-config FailureThreshold=1 \
        --query 'Service.Arn' \
        --output text \
        --region $AWS_REGION 2>/dev/null || \
    aws servicediscovery list-services \
        --filters "Name=NAMESPACE_ID,Values=${NAMESPACE_ID}" \
        --query "Services[?Name=='query-analyzer'].Arn" \
        --output text \
        --region $AWS_REGION)

    # Create ECS service
    aws ecs create-service \
        --cluster $CLUSTER_NAME \
        --service-name query-analyzer \
        --task-definition ${PROJECT_NAME}-query-analyzer \
        --desired-count 1 \
        --launch-type FARGATE \
        --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SG_ID],assignPublicIp=ENABLED}" \
        --service-registries "registryArn=${SERVICE_REGISTRY_ARN}" \
        --region $AWS_REGION 2>/dev/null || \
    aws ecs update-service \
        --cluster $CLUSTER_NAME \
        --service query-analyzer \
        --task-definition ${PROJECT_NAME}-query-analyzer \
        --force-new-deployment \
        --region $AWS_REGION

    log_success "Query Analyzer service deployed"
}

deploy_analytics() {
    log_info "Deploying analytics service..."

    # Create ECS service
    aws ecs create-service \
        --cluster $CLUSTER_NAME \
        --service-name analytics \
        --task-definition ${PROJECT_NAME}-analytics \
        --desired-count 1 \
        --launch-type FARGATE \
        --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SG_ID],assignPublicIp=ENABLED}" \
        --region $AWS_REGION 2>/dev/null || \
    aws ecs update-service \
        --cluster $CLUSTER_NAME \
        --service analytics \
        --task-definition ${PROJECT_NAME}-analytics \
        --force-new-deployment \
        --region $AWS_REGION

    log_success "Analytics service deployed"
}

# ═══════════════════════════════════════════════════════════════════
# Teardown
# ═══════════════════════════════════════════════════════════════════

teardown() {
    log_warn "This will delete ALL Epic 8 infrastructure. Are you sure? (yes/no)"
    read -r confirmation

    if [[ "$confirmation" != "yes" ]]; then
        log_info "Teardown cancelled"
        exit 0
    fi

    log_info "Starting teardown..."

    load_state

    # Delete ECS services
    for service in api-gateway query-analyzer generator analytics; do
        log_info "Deleting service: $service"
        aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $service \
            --desired-count 0 \
            --region $AWS_REGION 2>/dev/null || true
        aws ecs delete-service \
            --cluster $CLUSTER_NAME \
            --service $service \
            --force \
            --region $AWS_REGION 2>/dev/null || true
    done

    # Wait for services to be deleted
    sleep 30

    # Delete ECS cluster
    log_info "Deleting ECS cluster"
    aws ecs delete-cluster \
        --cluster $CLUSTER_NAME \
        --region $AWS_REGION 2>/dev/null || true

    # Delete ALB
    if [[ -n "$ALB_ARN" ]]; then
        log_info "Deleting ALB"
        aws elbv2 delete-load-balancer \
            --load-balancer-arn $ALB_ARN \
            --region $AWS_REGION 2>/dev/null || true
    fi

    # Wait for ALB to be deleted
    sleep 30

    # Delete target groups
    if [[ -n "$TG_ARN" ]]; then
        log_info "Deleting target group"
        aws elbv2 delete-target-group \
            --target-group-arn $TG_ARN \
            --region $AWS_REGION 2>/dev/null || true
    fi

    # Delete VPC resources
    if [[ -n "$VPC_ID" ]]; then
        log_info "Deleting VPC resources"

        # Delete subnets
        if [[ -n "$SUBNET_ID" ]]; then
            aws ec2 delete-subnet --subnet-id $SUBNET_ID --region $AWS_REGION 2>/dev/null || true
        fi

        # Detach and delete IGW
        if [[ -n "$IGW_ID" ]]; then
            aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID --region $AWS_REGION 2>/dev/null || true
            aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID --region $AWS_REGION 2>/dev/null || true
        fi

        # Delete security groups
        if [[ -n "$SG_ID" ]]; then
            aws ec2 delete-security-group --group-id $SG_ID --region $AWS_REGION 2>/dev/null || true
        fi

        # Delete route tables
        if [[ -n "$RTB_ID" ]]; then
            aws ec2 delete-route-table --route-table-id $RTB_ID --region $AWS_REGION 2>/dev/null || true
        fi

        # Delete VPC
        aws ec2 delete-vpc --vpc-id $VPC_ID --region $AWS_REGION 2>/dev/null || true
    fi

    # Delete CloudWatch log groups
    for service in api-gateway query-analyzer generator analytics; do
        log_info "Deleting log group: /ecs/${PROJECT_NAME}-${service}"
        aws logs delete-log-group \
            --log-group-name /ecs/${PROJECT_NAME}-${service} \
            --region $AWS_REGION 2>/dev/null || true
    done

    # Delete state file
    rm -f "$STATE_FILE"

    log_success "Teardown complete"
}

# ═══════════════════════════════════════════════════════════════════
# Status and Monitoring
# ═══════════════════════════════════════════════════════════════════

show_status() {
    log_info "Epic 8 Deployment Status"
    echo ""

    load_state

    # Check ECS services
    log_info "ECS Services:"
    for service in api-gateway query-analyzer generator analytics; do
        status=$(aws ecs describe-services \
            --cluster $CLUSTER_NAME \
            --services $service \
            --query 'services[0].status' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "NOT_FOUND")

        running=$(aws ecs describe-services \
            --cluster $CLUSTER_NAME \
            --services $service \
            --query 'services[0].runningCount' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "0")

        desired=$(aws ecs describe-services \
            --cluster $CLUSTER_NAME \
            --services $service \
            --query 'services[0].desiredCount' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "0")

        if [[ "$status" == "ACTIVE" && "$running" == "$desired" && "$running" != "0" ]]; then
            echo -e "  ${GREEN}✓${NC} $service: $running/$desired tasks"
        else
            echo -e "  ${RED}✗${NC} $service: $running/$desired tasks (status: $status)"
        fi
    done

    echo ""
    log_info "ALB Endpoint:"
    if [[ -n "$ALB_DNS" ]]; then
        echo "  http://$ALB_DNS"
        echo "  Health: http://$ALB_DNS/health"
    else
        echo "  Not available"
    fi

    echo ""
    log_info "Estimated Daily Cost: \$3.20"
}

show_logs() {
    load_state

    log_info "Select service to view logs:"
    echo "  1) api-gateway"
    echo "  2) query-analyzer"
    echo "  3) generator"
    echo "  4) analytics"
    read -p "Choice (1-4): " choice

    case $choice in
        1) service="api-gateway" ;;
        2) service="query-analyzer" ;;
        3) service="generator" ;;
        4) service="analytics" ;;
        *) log_error "Invalid choice"; exit 1 ;;
    esac

    log_info "Tailing logs for $service (Ctrl+C to exit)..."
    aws logs tail /ecs/${PROJECT_NAME}-${service} --follow --region $AWS_REGION
}

# ═══════════════════════════════════════════════════════════════════
# Main Command Handler
# ═══════════════════════════════════════════════════════════════════

main() {
    case "${1:-}" in
        setup)
            check_prerequisites
            setup_vpc
            setup_ecs
            setup_ecr
            setup_iam
            setup_alb
            setup_secrets
            setup_cloudwatch
            log_success "Infrastructure setup complete!"
            log_info "Next step: ./deploy.sh build"
            ;;

        build)
            check_prerequisites
            build_and_push
            log_success "Build complete!"
            log_info "Next step: ./deploy.sh deploy"
            ;;

        deploy)
            check_prerequisites
            deploy_services
            log_success "Deployment complete!"
            log_info "Next step: ./deploy.sh status"
            ;;

        teardown)
            teardown
            ;;

        status)
            show_status
            ;;

        logs)
            show_logs
            ;;

        test)
            load_state
            log_info "Running end-to-end tests..."
            curl -f "http://$ALB_DNS/health" || log_error "Health check failed"
            log_success "Tests passed"
            ;;

        *)
            echo "Epic 8 ECS Fargate Deployment Script"
            echo ""
            echo "Usage: $0 [command]"
            echo ""
            echo "Commands:"
            echo "  setup       - Create all infrastructure (VPC, ECS, ALB, etc.)"
            echo "  build       - Build and push Docker images"
            echo "  deploy      - Deploy services to ECS"
            echo "  teardown    - Delete all infrastructure"
            echo "  status      - Check deployment status"
            echo "  logs        - Tail service logs"
            echo "  test        - Run end-to-end tests"
            echo ""
            echo "Example workflow:"
            echo "  1. export HUGGINGFACE_TOKEN='your-token'"
            echo "  2. export OLLAMA_URL='https://your-ngrok-url.ngrok-free.app'"
            echo "  3. ./deploy.sh setup"
            echo "  4. ./deploy.sh build"
            echo "  5. ./deploy.sh deploy"
            echo "  6. ./deploy.sh status"
            exit 1
            ;;
    esac
}

main "$@"
